dist: xenial
sudo: required
language: c
matrix:
  include:
    - compiler: gcc
      env: configure_args='--enable-gcov'
    - compiler: clang
      env: configure_args=''
addons:
  apt:
    packages:
      - lcov
      - python3-docutils
      - python3-pip
      - python3-sphinx
install:
  - pip3 install pipenv
  - git clone --recursive https://github.com/stedolan/jq
  - cd jq &&
    cd docs && pipenv sync && cd .. &&
    autoreconf -vif &&
    ./configure --with-oniguruma=builtin --disable-maintainer-mode &&
    sudo env "PATH=$PATH" make install && cd ..
  - git clone https://github.com/varnishcache/varnish-cache.git
  - cd varnish-cache && ./autogen.sh && ./configure && make &&
    sudo make install && sudo ldconfig && cd ..
before_script:
  - ./autogen.sh
script:
  - ./configure CFLAGS="-Wall -Wextra -Werror" $configure_args
  - make check VERBOSE=1
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - make distcheck
